# Generated by Django 4.2.2 on 2023-06-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acidity1', models.CharField(max_length=200)),
                ('quantity1', models.CharField(max_length=200)),
                ('acidity2', models.CharField(max_length=200)),
                ('quantity2', models.CharField(max_length=200)),
                ('acidity3', models.CharField(max_length=200)),
                ('quantity3', models.CharField(max_length=200)),
                ('total', models.CharField(max_length=200)),
            ],
        ),
    ]
