# Generated by Django 4.2.2 on 2023-06-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_myform_result_alter_myform_acidity1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='acidity1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='myform',
            name='acidity2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='myform',
            name='acidity3',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='myform',
            name='quantity1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='myform',
            name='quantity2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='myform',
            name='quantity3',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='myform',
            name='result',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='myform',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
